// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	"newsapps/internal/features/articles"
	users "newsapps/internal/features/users"

	mock "github.com/stretchr/testify/mock"
)

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

// DeleteUserAccount provides a mock function with given fields: userID
func (_m *Query) DeleteUserAccount(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email
func (_m *Query) Login(email string) (users.Users, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 users.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (users.Users, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) users.Users); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(users.Users)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: newUser
func (_m *Query) Register(newUser users.Users) error {
	ret := _m.Called(newUser)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(users.Users) error); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserAccount provides a mock function with given fields: newUser
func (_m *Query) UpdateUserAccount(newUser users.Users) error {
	ret := _m.Called(newUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(users.Users) error); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuery creates a new instance of Query. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Query {
	mock := &Query{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// bagian query article
func (m *Query) CreateArticles(article articles.Article) error {
    args := m.Called(article)
    return args.Error(0)
}

func (m *Query) GetArticles() ([]articles.Article, error) {
    args := m.Called()
    return args.Get(0).([]articles.Article), args.Error(1)
}

func (m *Query) GetArticlesByID(id uint) (articles.Article, error) {
    args := m.Called(id)
    return args.Get(0).(articles.Article), args.Error(1)
}

func (m *Query) UpdateArticles(id uint, article articles.Article) error {
    args := m.Called(id, article)
    return args.Error(0)
}

func (m *Query) DeleteArticles(id uint, userID uint) error {
    args := m.Called(id, userID)
    return args.Error(0)
}