// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	users "newsapps/internal/features/users"

	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// DeleteUserAccount provides a mock function with given fields: userID
func (_m *Services) DeleteUserAccount(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email, password
func (_m *Services) Login(email string, password string) (users.Users, string, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 users.Users
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (users.Users, string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) users.Users); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(users.Users)
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: newUser
func (_m *Services) Register(newUser users.Users) error {
	ret := _m.Called(newUser)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(users.Users) error); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserAccount provides a mock function with given fields: newData
func (_m *Services) UpdateUserAccount(newData users.Users) error {
	ret := _m.Called(newData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(users.Users) error); ok {
		r0 = rf(newData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServices creates a new instance of Services. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
